print("My address is 3119 Jacob Hamblin Dr St George, UT 84790")
print()
print("I like to play guitar and watch movies in my free time.")
print()
print("I want to get rich and famous with the skills I learn at Utah Tech.")
print()
print("I have written in assembly, c, c++, c#, kotlin, swift, python, and js.")
print("Python and js are probs my favorite.")
print()
print("I have been attacked by dogs many times. After one incident, once the dog was wrestled off me, the owner said: ") 
print("'Sorry about that, he always goes straight for the nuts'.")
print()
